/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"
using namespace cv;

/* Header for class com_justinwei_purifiedwater_OpencvClass */

#ifndef _Included_com_justinwei_purifiedwater_OpencvClass
#define _Included_com_justinwei_purifiedwater_OpencvClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_justinwei_purifiedwater_OpencvClass
 * Method:    faceDetection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_justinwei_purifiedwater_OpencvClass_faceDetection
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_justinwei_purifiedwater_OpencvClass
 * Method:    skinDetection
 * Signature: (J)Lorg/opencv/core/Mat;
 */

Mat skinDetect(Mat& frame);

JNIEXPORT Mat JNICALL Java_com_justinwei_purifiedwater_OpencvClass_skinDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
